### ISSUE TITLE
Review of AOO41WG8

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#107] opened 2023-11-13 00:13 UTC
AOO41GS8-Working With Graphics is ready for next review.

**Comment by FJCC** [comment] 2023-11-14 00:45
I admit this is nit picking, but I don't want confusion to arise later. This issue's title mentions AOO41GS8-Working With Graphics, which would be a Getting Started Guide chapter and it doesn't exist. Chapter 8 of the Writer Guide is currently named AOOWG418-WorkingWithGraphics.odt. I think that should be AOO41WG8-WorkingWithGraphics.odt, though I'm not so sure that I'd risk just changing it without checking. Can you please confirm the file name and edit the issue title accordingly so we aren't confused later? Thanks!
Michele will work on this chapter as soon as I get it to her.

**Comment by knmc** [comment] 2023-11-14 18:48
Changed the tittle to properly reflect the chapter being reviewed.

**Comment by FJCC** [comment] 2023-11-14 21:46
Thanks, Keith!

**Comment by FJCC** [comment] 2023-11-20 20:34
Reviewed by Michele and FJCC. There are some new edits on page 4 and Fig. 16 was replaced because it was a duplicate of Fig. 17 and it didn't match the text. Also, some headers were changed to title case because they were missed previously.

**Closed as completed by FJCC** 2023-11-20 20:34 UTC
Labels: documentation, 4.1
